### ISSUE TITLE
Texture pack not on vehicles

### ISSUE THREAD

**Issue by MisterSoulZ** [ZombieStriker/QualityArmoryVehicles2#13]
Hi , i purchased plugin and i have quality armor, but texture pack not work for vehicles. It shows rabbit skin on vehicles...
Can you help me

**Comment by Lorenzo0111** [comment]
What spigot version are you using? What plugin version are you using?

**Comment by KleinWunder** [comment]
I have a similar/the same issue.
I am using the latest version of QAV on a 1.12.2 Server.
The automatic resource pack does only show the no-texture item instead of cars

**Comment by Lorenzo0111** [comment]
Try setting this as **qualityarmory** ( **not** qualityarmoryvehicles ) texture: https://www.dropbox.com/s/2grkgbgmovyqmw0/QualityArmoryV2.1.9.zip?dl=1

**Comment by KleinWunder** [comment]
It did not work. The Resource-Pack is shown as incompatible and textures do not apply

**Comment by KleinWunder** [comment]
How long will this take? Or how do I change what Itemstack is used for vehicles? Because all I see is that the material is changeable.

**Comment by Lorenzo0111** [comment]
I’ll fix it ASAP

**Comment by Lorenzo0111** [comment]
I found the bug, I'm working on it

**Comment by Lorenzo0111** [comment]
The problem is caused from an invalid resource pack. You have to find the correct 1.12.2 qav resourcepack (I'm sorry but I can't find it) and put it in your configuration.
