### ISSUE TITLE
Three simple questions

### ISSUE THREAD

**Issue by ajh123** [ZombieStriker/QualityArmoryVehicles2#146]
This plugin is excellent!

**One**
How do I stop a plane?

**Two**
How do I increase the turning speed of all land vehicles 

~~**Three**
How do I break a vehicle that is on the ground without ```/qav callback```~~

**Comment by ajh123** [comment]
Ok I found the solution to **three** just shift and right click on the driver seat

**Comment by Lorenzo0111** [comment]
Hey, thanks for opening an issue.
Sorry for the delays in my replies.

1. Actually there is a bug that makes it harder, will fix this asap. For now you can try stopping it by pressing S

2. You manually need to do this for all the vehicles in their configuration file

**Comment by ajh123** [comment]
Thank you! Hopefully the plane bug gets fixed!
