### ISSUE TITLE
Important bug with duplicate armor-stands

### ISSUE THREAD

**Issue by Felson999** [ZombieStriker/QualityArmoryVehicles2#156]
This is a very dangerous bug. After the unloaded of a chunk, a duplicate equipment may sometimes appear. If you unload a chunk, then return to it and type the /qav removeBugged command, then the vehicles will clear. Regardless of the version of the core and other factors. We learned this after the players began to massively find armor stands without vehicles, there were invisible armor stands after the unload of chunks. Having found the hitbox, it was possible to pick up a duplicate, but this is sometimes. Please note

Video: https://www.dropbox.com/s/vngk20qs6v1q70i/video%20bug.rar?dl=1

**Comment by Lorenzo0111** [comment]
Are you running some plugin such as clearlag?

**Comment by Felson999** [comment]
I checked on a server without such plugins, it was also duplicated there.

**Comment by Lorenzo0111** [comment]
Can you try with the latest release?
