### ISSUE TITLE
Vehicles are uncontrollable , they shift far left far right (not moving straight) and moutning them is almost impossible

### ISSUE THREAD

**Issue by el211** [ZombieStriker/QualityArmoryVehicles2#160]
-Vehicles are not working as intend to  they dont move straight 
they either shift far right and far left

- Vehicles are unctorllable , the vehicles control us rather then we control them

- Mounting vehicles is terrible , its not consistent at all

https://cdn.discordapp.com/attachments/737993530278150186/1025742359272640572/Lunar_Client_1.18.2-1b4bfc6_master_2022-10-01_15-10-37.mp4

here is the video proof

**Comment by Lorenzo0111** [comment]
How are you placing the vehicle? with the item or a command?

**Comment by el211** [comment]
i give myself the vehicle the place it with my hanb

**Comment by Lorenzo0111** [comment]
Can you provide your plugin list?

**Comment by el211** [comment]
![image](https://user-images.githubusercontent.com/86126606/208319966-adb2864e-8d6b-4fd3-bdf8-b74ce5ce892d.png)

**Comment by Lorenzo0111** [comment]
Are you able to test on a clean server with just ProtocolLib and QualityArmoryVehicles? Also what is your server version?

**Comment by el211** [comment]
i am using purpur 1.18.2 
do u want my  server plugins folder ?

**Comment by Lorenzo0111** [comment]
Okay, could you do the test i asked above?

**Comment by el211** [comment]
@Lorenzo0111

**Comment by el211** [comment]
i dont have another test server this would mean deleting all my plugins

**Comment by Lorenzo0111** [comment]
> Are you able to test on a clean server with just ProtocolLib and QualityArmoryVehicles?

^^

**Comment by el211** [comment]
> i dont have another test server this would mean deleting all my plugins

i can send u my plugins folder or even give u my console access

**Comment by Lorenzo0111** [comment]
If you could test in a clean server it would be good

**Comment by matytyma** [comment]
> I don't have another test server, this would mean deleting all my plugins.

@el211 You can just download the plugins and them put them back, you can also start a testing server on localhost.

**Comment by Lorenzo0111** [comment]
Are you able to do that? @el211
