### ISSUE TITLE
Right click (without crouch) bypasses candrive permission check

### ISSUE THREAD

**Issue by Boothin** [ZombieStriker/QualityArmoryVehicles2#179]
Like the title says, using luckperms and checking the verbose logs, with the require perms to drive set to true.. if a player simply right clicks a car it lets them into the driver seat and lets them drive it, without having the perms because it doesn't check the perms, If they try to use the GUI it does not let them into the driver seat as expected as it does check the perms.

**Comment by Lorenzo0111** [comment]
Please provide your vehicle configuration

**Comment by Vayler1** [comment]
I have the same problem as this person. Here is my car configuration:
vehicle_type: Car
name: tesla
id: 45
displayname: Tesla
center:
  ==: Vector
  x: 0.3
  y: -2.05
  z: -0.7
front_vector_offset: 3.25
back_vector_offset: 2.45
passagers:
- ==: Vector
  x: 0.1
  y: 2.65
  z: 1.5
- ==: Vector
  x: -1.2
  y: 2.65
  z: 1.5
- ==: Vector
  x: -1.2
  y: 2.85
  z: 0.0
- ==: Vector
  x: -1.2
  y: 2.85
  z: 0.7
stopMeleeDamage: true
useStaticTurning: false
RequiresFuel: true
widthOffset: 0.74
heightOffset: 2.0
vehicle_texture_material: RABBIT_HIDE
maxHealth: 100.0
cost: 2000
InputManager:
  keys:
    LMB: HONK
    F: none
    RMB: none
ItemLore:
- '&7Press [Space] to break'
- '&7Press [LMB] to honk'
TurnSpeedInRadians: 0.059269908169872414
activation_radius: 2
trunksize: 9
allowedInShop: false
maxAcceleration: 1.9
baseAcceleration: 0.065
maxReverseAcceleration: 1.05
canJumpOnBlocks: true
jumpHeight: 0.55
model:
  ModelSize: TURTLE
canDeconstructByEnvironment: true
rotationMultiplier: 1
sound: driving
soundVolume: 1
driverseat:
  UseOffsetSeatFromModel: false
  Offset:
    ==: Vector
    x: 0.3
    y: -0.15
    z: -0.7
lastModifiedByQA: 1677844793813

**Comment by Lorenzo0111** [comment]
I will check tomorrow

**Comment by Lorenzo0111** [comment]
Are you sure about this? I can't reproduce the issue. Is the vehicle public maybe?

**Comment by Lorenzo0111** [comment]
Okay, keep me updated
