### ISSUE TITLE
Custom Vehicles are too small

### ISSUE THREAD

**Issue by EarthCraftOfficial** [ZombieStriker/QualityArmoryVehicles2#2]
I personally made a custom model/texture for a new jeep. I copied the same example jeep config and just added a new texture to the new one. for some reason it looks really small
![image](https://user-images.githubusercontent.com/64188616/116511238-7ead0480-a909-11eb-946b-66d88acaabab.png)

**Comment by KleinWunder** [comment]
Can't you just resize it in whatever program you originally made it in?

**Comment by Lorenzo0111** [comment]
It isn't releated to the plugin, try to resize your model

**Comment by KleinWunder** [comment]
How is the resource pack that comes with the plugin and is provided by the plugin owner not related?
