### ISSUE TITLE
cars move without pressing any keys (API PROBLEM)

### ISSUE THREAD

**Issue by DEADLYDEVIL-SPIGOT** [ZombieStriker/QualityArmoryVehicles2#21]
here's the code i use to spawn vehicle
`String[] sloc = ConfigManager.get_config("car_training").getStringList("waypoints").get(1).split(",");
        Location loc = new Location(player.getWorld(),Integer.parseInt(sloc[0]),Integer.parseInt(sloc[1]),Integer.parseInt(sloc[2]));
        VehicleEntity vehicle = QualityArmoryVehicles.spawnVehicle(new AbstractCar("moskvitch",2),player);
        vehicle.setFuel(100);`
here's the video

https://user-images.githubusercontent.com/64157024/129440290-bb69385c-adcf-4b80-83a3-cb80f3e276c5.mp4

**Comment by DEADLYDEVIL-SPIGOT** [comment]
the problem is where when i press W key car will move backward and when i press S it will move forward

**Comment by Lorenzo0111** [comment]
ok

**Comment by Lorenzo0111** [comment]
I can't reporuce this issue, it works fine for me.
Can you send me some infos about your environment? (server version,plugin version..)
Code:
```java
VehicleEntity vehicle = QualityArmoryVehicles.spawnVehicle(QualityArmoryVehicles.getVehicle("moskvitch"),(Player) sender);
vehicle.setFuel(100);
vehicle.getDriverSeat().setPassenger((Player) sender);
```

**Comment by DEADLYDEVIL-SPIGOT** [comment]
1.16.4 paper
latest version of quality armory vehicles

**Comment by Lorenzo0111** [comment]
Can you try with the code I mentioned above?
