### ISSUE TITLE
Issue during callback

### ISSUE THREAD

**Issue by matytyma** [ZombieStriker/QualityArmoryVehicles2#211]
> On my 1.19.3 Paper server vehicles just get stuck at random. I'm also getting this error in my console when I try to callback.

![image](https://user-images.githubusercontent.com/100159609/222508800-56b56bf1-0176-4744-92bc-eef9e6f558bd.png)

**Comment by Lorenzo0111** [comment]
The trunk size must be a multiple of 9. Check again in the `trunksize` option of your vehicle configuration
