### ISSUE TITLE
[Bug]: in new version of plugin

### ISSUE THREAD

**Issue by Vayler1** [ZombieStriker/QualityArmoryVehicles2#214]
In the new version of the plugin, in which the tp has been removed if you ride in a car seat: 
1. The public function of the car does not work, that is, if I make it public, the person cannot sit down, it is necessary only through the car menu. 
2. Now you can get into the car only through the menu, and not by clicking on the door, as before

**Comment by TheKimiNoUso** [comment]
Pretty sure @Lorenzo0111 fixed this in Issue #161, but he's yet to actually upload it to Spigot
