### ISSUE TITLE
Whitelist Issue

### ISSUE THREAD

**Issue by oZinth** [ZombieStriker/QualityArmoryVehicles2#215]
People can't get in my car without being whitelisted first, even though I used the permission you put on [Spigot](https://www.spigotmc.org/resources/qualityarmory-vehicles-2.59129/) `qualityarmoryvehicles.overrideWhitelist : Lets a user ride a vehicle, even if they are not in the whitelist for that vehicle.`

**Comment by Lorenzo0111** [comment]
Please provide your vehicle configuration.

**Comment by Lorenzo0111** [comment]
@oZinth
