### ISSUE TITLE
Add support for SurvivalPlus

### ISSUE THREAD

**Issue by ErythroCraft** [ZombieStriker/QualityArmoryVehicles2#23]
This Issue is a question about to import the plugin SurvivalPlus.

So, I'm using the plugin [SurvivalPlus](https://github.com/ShaneBeeStudios/SurvivalPlus) on my server.
With this plugin I make my server better to play survival in real parts of food and energy.

**Can you give an update to fill energy while player are sitting on vehicles?**

**Comment by Lorenzo0111** [comment]
I'm not sure about what you are suggestion. can you explain ?

**Comment by ErythroCraft** [comment]
The SurvivalPlus plugin has got the future '' Energy ''.
Working, fighting and other movements (jumping, walking, running, flying and swimming) use up energy.
The plugin itself has a function for chairs. As soon as a player sits down on a chair, the energy is replenished.

Now the player should be able to replenish their energy while sitting in cars, on motorcycles or the like.

**Comment by Lorenzo0111** [comment]
Ok, I’ll create an addon for that

**Comment by ErythroCraft** [comment]
Perfect and spacial thanks.  
     
<°-°>

**Comment by Lorenzo0111** [comment]
@ErythroCraft the plugin seems to not have an api, so I can't add the support

**Comment by ErythroCraft** [comment]
Ah, ok.

Mmh, maybe in a future you or other people can create a better plugin that is doing this.

Thanks for looking
