### ISSUE TITLE
[Bug]: Player seat [Y] coordinate can't be change, no matter what is the car. Etc

### ISSUE THREAD

**Issue by SimplyArchieChow** [ZombieStriker/QualityArmoryVehicles2#235]
### Maybe something that you need to know
I'm currently using the latest version of QualityArmoryVehicle and the QualityArmory.
and I'm running in Minecraft Paper Version 1.18.2 #388
I have also tested a clean installation, but I am still unable to sit in the Red Bumper Car. Instead, I appear to be floating above it.

### Problem

- The [Y] coordinate for seat height is not functioning properly, and you can also check the default Red Bumper Car it's also not working.
- The range for players to right-click and enter the car is too small or difficult to find., and player need to click aimlessly around the car before they can enter the car.

### Image
![image](https://user-images.githubusercontent.com/132149191/235310768-572db54e-328d-4534-ad37-4fd36bcbca4d.png)
![image](https://user-images.githubusercontent.com/132149191/235310807-e60b2236-a5c6-477b-95bb-d91f07e571d3.png)

**Comment by Lorenzo0111** [comment]
@SimplyArchieChow
