### ISSUE TITLE
Wrong passengers visual

### ISSUE THREAD

**Issue by Lorenzo0111** [ZombieStriker/QualityArmoryVehicles2#24]
There is a strange bug I'm working on: I created an armorstand for each passenger and when the main one moves, with some math and vectors the other one goes with it.

Now, from my main account I see everything normal(image 1) but from the other one I see a strange thing: I see myself standing on and I can walk, without any armorstand(image 2)

![](https://i.gyazo.com/523320430e114486f8100f9b484d3de0.png)
![](https://i.gyazo.com/164646db4aca6c421f6db0b44e57d1a8.png)

**Comment by Lorenzo0111** [comment]
Waiting for: https://hub.spigotmc.org/jira/browse/SPIGOT-6733

**Comment by ChatpKSK** [comment]
I have this problem too.
- Paper 1.17.1

**Comment by Lorenzo0111** [comment]
@ChatpKSK this may be a client-side problem so I think for now I can't do anything
