### ISSUE TITLE
2 Bugs Report World Guard Bug And /qav callback or /qav callbackall

### ISSUE THREAD

**Issue by Prowco** [ZombieStriker/QualityArmoryVehicles2#248]
The first one is world guard support is not working properly if i add the flags vehicle-place or vehicle-destroy users cant interact with vehicles or drive or open the menu
[https://i.gyazo.com/9887c5e64ac17c5b1df61ba63ab3729f.png](url)

The Second bug is if you spawn a vehicle and you have the garage option enable if you put /qav callback or callbackall the vehicles returns to your garage but the vehicle duplicates and keep on the map too. 
[https://i.gyazo.com/1b981f7578de8757488c06f4eaae9efb.png](url)

**Comment by Lorenzo0111** [comment]
Can't reproduce the second issue, please provide your config.yml

**Comment by Prowco** [comment]
[config.txt](https://github.com/ZombieStriker/QualityArmoryVehicles2/files/11808060/config.txt)

**Comment by Prowco** [comment]
qav removevehicle namevehicle still not work you keep the vehicle in your garage there is no any option for remove vehicles from your garage and old versions have this option 
world guard flag for drive vehicles still dont work it say you dont have permissions
and yes i already reported all this in github and you just close the ticket with out solve anything -.-
the gui menu of each car sometimes works and anothers not is pretty hard to open it with out op
options remove vehicle on player quit dont work also the car still on the map
when player leaves the server
Also when you use qav callback or callbackall dosent work you get your vehicle in your garage yes but the vehicle dont get removed from the map so at the ends it duplicates
and garage is bugged too -.- if you spawn a car from your garage and then you open the garage again and spawn the same car you can duplicate infinite the cars, i mean the car should be removed from garage but no you can spawn all the cars you want.
Also limit vehiclelimiter dont work to you can buy as many cars you want

**Comment by Lorenzo0111** [comment]
- [ ] WorldGuard support
- [ ] Callback not working
- [ ] RemoveVehicle not working
- [ ] Difficult hitbox
- [ ] Remove on quit not working
- [ ] Garage spawn and callback duplicates
- [ ] Vehiclelimiter not working

**Comment by Prowco** [comment]
> > Also limit vehiclelimiter dont work to you can buy as many cars you want
> 
> The vehicle limiter only blocks you from placing the cars, not from purchasing them

In all the case you can spawn as many vehicles you want also with this config on true.

**Comment by Prowco** [comment]
do you close the ticket do you already fix all the errors and bugs i report?

**Comment by Prowco** [comment]
WorldGuard support
 Callback not working
 RemoveVehicle not working
 Difficult hitbox
 Remove on quit not working
 Garage spawn and callback duplicates
 Vehiclelimiter not working

And as i mentioned the old version of quality armory vehicles have a command for remove some car from garage for any user bc if not how in the world i am going to control the cars users have? i mean there is no sense that new version of QAV dont have any option for remove vehicles from garage in case admins need to do it
