### ISSUE TITLE
Tanks don't fire

### ISSUE THREAD

**Issue by Vayler1** [ZombieStriker/QualityArmoryVehicles2#252]
I wanted to shoot a tank on my server, but I saw that they do not shoot. I tried to sit in all the passenger seats, called people to sit down, etc., but it didn't help. I think this is a bug that needs to be fixed

**Comment by Lorenzo0111** [comment]
Please provide steps about how to reproduce the issue, expected behaviour and actual behaviour

**Comment by Vayler1** [comment]
Ah, well, you can make it possible to shoot fireballs like in the vehicles plugin, you just sit in the tank, press the fireball button and shoot

**Comment by Lorenzo0111** [comment]
I'm not sure, are you making a suggestion?
