### ISSUE TITLE
Sometimes will generate two vehicles

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmoryVehicles2#28]
no conditions, happens 1~2 out of 20 times
![image](https://user-images.githubusercontent.com/36799194/135356912-4b27c1d6-1629-4897-ac51-a391579a4cc7.png)

**Comment by Lorenzo0111** [comment]
How are you spawning the vehicle?

**Comment by WongIong** [comment]
Just right click on the floor, no other conditions

**Comment by Lorenzo0111** [comment]
Are you in creative mode?

**Comment by WongIong** [comment]
Yes

**Comment by Lorenzo0111** [comment]
If you press the button for more than one second it will spawn two vehicles (only if you are in creative mode), this is a minecraft bug, I may add a cooldown but it will create other issues.

**Comment by WongIong** [comment]
Nvm if is a minecraft bug
I do press the button less than 1 second.
