### ISSUE TITLE
1.21.2/1.21.3/1.21.4 support?

### ISSUE THREAD

**Issue by ShadowTigerCool** [ZombieStriker/QualityArmoryVehicles2#320]

**Comment by Lorenzo0111** [comment]
https://discord.com/channels/1088775598337433662/1088777745623957535/1304380653458165802

![image](https://github.com/user-attachments/assets/bd088f8b-e858-444d-bd4c-1d100edd92ad)

I expect to publish the update this week if I can

**Comment by ShadowTigerCool** [comment]
Any updates on this?

**Comment by ShadowTigerCool** [comment]
Any updates on this?

**Comment by Lorenzo0111** [comment]
I will try working on this tomorrow
