### ISSUE TITLE
UFO

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmoryVehicles2#33]
1. it is very very hard to get on a UFO, you are not able to find its hitbox.
2. = = every time you get on it, it honked

**Comment by Lorenzo0111** [comment]
I can't reproduce there issues. If this persist with the latest version please open again the issue

**Comment by WongIong** [comment]
The UFO is still having this issue with the latest version.

**Comment by Lorenzo0111** [comment]
I’ve fixed it with the latest commit. I’ll release it soon

**Comment by WongIong** [comment]
great
