### ISSUE TITLE
Is it a texture bug?

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmoryVehicles2#34]
![image](https://user-images.githubusercontent.com/36799194/135359045-8e82dfa9-ff66-4193-8024-45a7a54397e6.png)
Also it has a "&7" in the lore
![image](https://user-images.githubusercontent.com/36799194/135359068-0b5acdc1-1643-42d3-9f39-9009f1590007.png)

**Comment by Lorenzo0111** [comment]
No, this isn’t a bug because there isn’t any wrench texture for now but I’ll add it soon. 
I’ll fix the lore soon

**Comment by WongIong** [comment]
ok
