### ISSUE TITLE
Horns honked not only when LMB get clicked

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmoryVehicles2#37]
It is also honked  when you throw something

**Comment by Lorenzo0111** [comment]
I'm not very sure about this bug- Can you make a video to demostrate it?

**Comment by WongIong** [comment]
https://youtu.be/_OBLJgli_cA
i didnt press my LMB in the whole time

== this video also included another issue:
U get off from Vehicles> It disappear unless you /qav callback.
