### ISSUE TITLE
Keep vehicles away from y:256

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmoryVehicles2#48]
When your vehicle was stuck in somewhere
you turned it to the right path
the speed of the vehicle would increased to a horror level.

this is how it looks like at the end: https://youtu.be/bwcBgng2Edc
i think it is force stopped by paper?
you can't get out of the vehicle in this case.
LMB RMB F SPACE SHIFT are not working

**Comment by Lorenzo0111** [comment]
Hello, this issue may be:

1. A clientside bug
2. An anticheat issue, are you running any anticheat?

**Comment by WongIong** [comment]
1. I have used clean version of minecraft, also wurst client. They both like this.
2. It was a clean server, only some dependences.
3. Version is 1.16.5 paper 783.

**Comment by Lorenzo0111** [comment]
4: Yeah, that may be the issue

**Comment by WongIong** [comment]
If it is possible to keep vehicles away from y: 256?
