### ISSUE TITLE
question/suggestion helicopters controls

### ISSUE THREAD

**Issue by cmod31** [ZombieStriker/QualityArmoryVehicles2#51]
hey it would be cool if the helicopters just go higher if you press spacebar and not that if you hit spacebar it flies in the direction the player is viewing. also sounds for the vehicles in general would be cool

**Comment by Lorenzo0111** [comment]
> i meant more sounds also the hitbox doesn't work at all if you have luck you find the right angle to rightclick one seat and when you change seats you can't change it back

You have to right click the driver seat to interact with the vehicle
