### ISSUE TITLE
Disappearing

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmoryVehicles2#75]
A player on my server told me that his car suddenly disappeared without any signs while he was driving it.

**Comment by Lorenzo0111** [comment]
It's quite impossible to fix a bug that can't be reproduced. When this happens? Does it disappear or just callback?

**Comment by WongIong** [comment]
It disappeared without giving it back.
Yes i knew it, but i think it would be better that if i report it here first.

**Comment by Lorenzo0111** [comment]
Ok, while I do some tests please try to find when this happens
