### ISSUE TITLE
Flight

### ISSUE THREAD

**Issue by WongIong** [ZombieStriker/QualityArmoryVehicles2#77]
So if you are in survival mode and you drive a vehicle.
you may get kick from the server if allow-flight in server config is disabled.

**Comment by Lorenzo0111** [comment]
Are you using spigot or paper?

**Comment by WongIong** [comment]
paper

**Comment by Lorenzo0111** [comment]
does this happens only on a plane or on every vehicle?

**Comment by WongIong** [comment]
Tested on a few of cars.
