### ISSUE TITLE
The function of a vehicle sometimes disappears

### ISSUE THREAD

**Issue by cmod31** [ZombieStriker/QualityArmoryVehicles2#81]
Sometimes (for me after a server restart) the vehicle just stops working and you can't call it back with a command.
/kill @e[type=minecraft:armor_stand] does work but its not how it should be.
Also the hitboxes are way to small you still have to try to find them

**Comment by Lorenzo0111** [comment]
What version of the plugin are you using? Don't say latest

**Comment by cmod31** [comment]
It says 2.1

**Comment by Lorenzo0111** [comment]
Can't reproduce.
are you using some clear-lag plugin?

**Comment by cmod31** [comment]
Yes but it doesn't delete entitys

**Comment by cmod31** [comment]
It could have been a paper armorstand bug idk but i didn't have this issue again for some time
