### ISSUE TITLE
Ideas for QAV

### ISSUE THREAD

**Issue by DED0KOT** [ZombieStriker/QualityArmoryVehicles2#86]
- [x] Change the control of airplanes and helicopters as in the vehicles plugin. (It's much more convenient) 
- [x] Add tractor, tank and drilling machine

**Comment by ADM8** [comment]
I believe there is already a tank in the plugin but I'm not sure if in its current state it works. Would be cool to see a tractor and other vehicles that can build and break, makes mechanization a much more powerful tool.
