### ISSUE TITLE
Gui problems

### ISSUE THREAD

**Issue by atesson19** [ZombieStriker/QualityArmoryVehicles2#93]
Hi , i have troubles with vehicles gui , When i change speed or smth like this , fuel gui and others stops working
![image](https://user-images.githubusercontent.com/98190760/150677591-ce3e467a-7987-4ccd-968b-8f9436570ef4.png)
![image](https://user-images.githubusercontent.com/98190760/150677594-47ce90a5-8376-4723-a730-139cd730cbb4.png)

**Comment by Lorenzo0111** [comment]
Can you send me that config as text?

**Comment by atesson19** [comment]
prefix: '&6[QA-Vehicles]&f'
USE_1_13_MODEL_SYSTEM: false
enable_VehicleLimiter: false
enable_PickupVehicles: true
enable_UnlockableVehicles: false
enable_GarageCallback: false
enable_RequirePermsToDriveType: false
enable_SetOwnerOnVehicleSpawn: true
enable_VehicleDamage: true
enable_Debug_RemoveFuelChecks: false
enable_SetOwnerOfVehicleIfUnowned: false
Enable_Creation_Of_Default_Files: true
enable_RemoveVehiclesOnDismount: false
enable_RemoveVehiclesOnPlayerQuit: false
enable_DestroyVehiclesOnPlayerQuit: false
enable_StopCreativeDuplication: false
enable_VehiclePlayerCollision: true
enable_SwapEndermiteWithCheckenForLowRider: false
enable_FuelCarsWhenSpawnedFromGarage: true
enable_PushCarsOnCrash: true
enable_PushEntityOnCollide: true
enable_UseHeadsForGUI: true
ENABLE_DEBUG: false
override_debug_withCommand: false
enable_AntiCheatHook: false
freezeOnDestroy: false
bypassCoalInCreative: true
sendActionBarOnMove: true
enableShopCooldown: false
enable_RequirePermToBuyVehicle: false
enable_VehiclesHaveTrunks: true
blockAccelerationReduction:
  BLOCK_NAME: 1.0
enable_RemoveVehiclesOnEmpty: false
BlacklistedWorlds:
- example_world_name
maxYHeight: 256
enable_useChatForOutOfdFuelMessage: false
QAMini:
  resourcepackurl: https://github.com/ZombieStriker/QualityArmory-Resourcepack/releases/download/v2.1.9/QualityArmory.zip
hooks:
  WorldGuard: true
And vehicles config
vehicle_type: Car
name: tgr
id: 18
displayname: Тигр
center:
  ==: Vector
  x: 0.0
  y: 0.0
  z: 0.0
front_vector_offset: 3.25
back_vector_offset: 3.45
passagers:
- ==: Vector
  x: 0.0
  y: 1.0
  z: 1.0
- ==: Vector
  x: -1.2
  y: 1.0
  z: 0.5
- ==: Vector
  x: -1.2
  y: 1.0
  z: 0.0
- ==: Vector
  x: -1.2
  y: 1.0
  z: 1.0
stopMeleeDamage: true
useStaticTurning: true
RequiresFuel: true
widthOffset: 0.74
heightOffset: 2.5
vehicle_texture_material: RABBIT_HIDE
maxHealth: 150.0
cost: 1850
InputManager:
  keys:
    F: 40mm_LAUNCHER
    LMB: HONK
    RMB: none
ItemLore:
- '&7Нажмите [пробел] что бы стрелять'
- '&7Займите место пассажира , что бы стрелять из пушек.'
TurnSpeedInRadians: 0.039269908169872414
activation_radius: 20
trunksize: 3
allowedInShop: true
maxAcceleration: 0.3
baseAcceleration: 0.065
maxReverseAcceleration: 0.45
canJumpOnBlocks: true
jumpHeight: 0.55
model:
  ModelSize: ADULT_ARMORSTAND_HEAD
canDeconstructByEnvironment: true
rotationMultiplier: 1
sound: driving
soundVolume: 1
driverseat:
  UseOffsetSeatFromModel: true
  Offset:
    ==: Vector
    x: 0.0
    y: -1.0
    z: 0.0
lastModifiedByQA: 1642171123903

**Comment by atesson19** [comment]
Can you do it faster ?1000 people wait you and vehicles

**Comment by Lorenzo0111** [comment]
Can you try to reproduce the issue without any other plugin?

**Comment by atesson19** [comment]
wihtout other plugins its same problem 
i test it with 1.16.5 airplane / 1.16 spigot , same issues and dont know why . Can java version cause this problem?

**Comment by Lorenzo0111** [comment]
Can you reproduce the error with the default configuration and messages by changing a config field at once to find what's the one who causes the error?

**Comment by atesson19** [comment]
i try , and it can cause by name / reverse speed and trunksize

**Comment by Lorenzo0111** [comment]
Are you reloading the plugin with PlugMan?
