### ISSUE TITLE
WorldGuard integration gives error

### ISSUE THREAD

**Issue by KahpotVanilla** [ZombieStriker/QualityArmoryVehicles2#94]
Hey, when I go near a worldguard region with a car, it spams the console with this error message:
[https://pastebin.com/SNReHm3L](https://pastebin.com/SNReHm3L)
How do I fix it?

**Comment by KahpotVanilla** [comment]
I got Task #7666 now after a restart, it's the same as #8399

**Comment by Lorenzo0111** [comment]
Are you using WorldGuard?

**Comment by KahpotVanilla** [comment]
> Are you using WorldGuard?

Yes, I am using WorldGuard

**Comment by KahpotVanilla** [comment]
any update?

**Comment by Lorenzo0111** [comment]
Server version? WorldGuard version?

**Comment by KahpotVanilla** [comment]
> Server version? WorldGuard version?

Paper version: Paper-790
Worldguard version: 7.0.5
Minecraft version: 1.16.5
